version: "3.9"
services:
  mysql:
    image: mysql:8.0
    container_name: db
    restart: always
    volumes:
      - db-store:/var/lib/mysql
      - ./logs:/var/log/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - TZ=${TZ}
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 13306:3306
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    hostname: azurite
    restart: always
    command: "azurite --blobHost 0.0.0.0 --blobPort 10000 --queueHost 0.0.0.0 --queuePort 10001"
    ports:
      - "10000:10000"
      - "10001:10001"
    volumes:
      - ./data:/data
    networks:
      - dapr_template
    environment:
      # ref: https://github.com/Azure/Azurite/issues/1615#issuecomment-1196332300
      - AZURITE_ACCOUNTS=devstoreaccount1:Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==
      - TZ=Asia/Tokyo
  python_app:
    build: ./python
    volumes:
      - ./python:/app/
    ports:
      - "8000:8000"
    networks:
      - dapr_template
    depends_on:
      - azurite
      - placement
  python_app_dapr:
    image: "daprio/daprd:edge"
    command: [
        "./daprd",
        "--app-id",
        "python_app",
        "--app-port",
        "8000",
        "--placement-host-address",
        "placement:50006", # Dapr's placement service can be reach via the docker DNS entry
        "--resources-path",
        "./components",
      ]
    volumes:
      - "./dapr-components/:/components" # Mount our components folder for the runtime to use. The mounted location must match the --resources-path argument.
    depends_on:
      - python_app
    network_mode: "service:python_app" # Attach the python_app-dapr service to the python_app network namespace
  node_app:
    build: ./nodejs
    volumes:
      - ./nodejs:/usr/src/app
    ports:
      - "3000:3000"
    networks:
      - dapr_template
    depends_on:
      - azurite
      - placement
      - mysql
  node_app_dapr:
    image: "daprio/daprd:edge"
    command: [
        "./daprd",
        "--app-id",
        "node_app",
        "--app-port",
        "3000",
        "--placement-host-address",
        "placement:50006", # Dapr's placement service can be reach via the docker DNS entry
        "--resources-path",
        "./components",
      ]
    volumes:
      - "./dapr-components/:/components" # Mount our components folder for the runtime to use. The mounted location must match the --resources-path argument.
    depends_on:
      - node_app
    network_mode: "service:node_app"
  placement:
    image: "daprio/dapr:edge"
    command: ["./placement", "--port", "50006"]
    ports:
      - "50006:50006"
networks:
  dapr_template:
    external: true
volumes:
  db-store:
